[package]
name = "netdox"
version = "0.1.0"
edition = "2021"

[dependencies]
age = "0.9.2"
clap = { version = "4.3.4", features = ["derive"] }
paris = { version = "1.5.15", features = ["no_logger", "macros"] }
redis = "0.23.0"
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.4"

[features]
default = ["pageseeder"]
pageseeder = []
