[package]
name = "netdox"
version = "0.1.0"
edition = "2021"

[dependencies]
age = "0.9.2"
clap = { version = "4.3.4", features = ["derive"] }
redis = "0.23.0"
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.4"
